baseURL: "https://blog.gnehs.net"
title: 勝勝
paginate: 7
theme: paper
languageCode: zh-TW

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

permalinks:
  posts: "/:filename/"
  categories: "/categories/:slug/"

author:
  name: 勝勝
  homepage: https://gnehs.net
menu:
  main:
    - identifier: about
      name: 關於
      url: /about/
      weight: 0
    - identifier: categories
      name: 分類
      url: /categories/
      weight: 20
    - identifier: invite
      name: 邀請碼
      url: /invite-codes/
      weight: 10
