baseURL: "https://examplesite.com"
title: 勝勝
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true
    
Taxonomies:
  category: "categories"
  tag: "tags"
  series: "series"
params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: 勝勝
    description: "ExampleSite description"
    author: gnehs
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]

    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: false
    ShowShareButtons: false
    disableSpecial1stPost: false
    comments: false
    hidemeta: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "https://gnehs.net/img/avatar.svg"
        favicon16x16: "https://gnehs.net/img/avatar.svg"
        favicon32x32: "https://gnehs.net/img/avatar.svg"
        apple_touch_icon: "https://gnehs.net/img/avatar.svg"
        safari_pinned_tab: "https://gnehs.net/img/avatar.svg"

    label:
        text: "Home"
        icon: "https://gnehs.net/img/avatar.svg"
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "https://gnehs.net/img/avatar.svg"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "嗨"
        Content: 這裡是勝勝的部落格

    socialIcons:
        - name: user
          url: "https://gnehs.net/"
        - name: facebook
          url: "https://www.facebook.com/gnehsowo"
        - name: github
          url: "https://github.com/gnehs"
        - name: instagram
          url: "https://www.instagram.com/gnehsowo/"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: about
          name: about
          url: /about/
          weight: 0
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20 
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
