name: Github-Pages

on:
  push:
    branches:
      - ❤️
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.8'
      - name: Setup Node v16
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.1'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.81.0'
          extended: true
      - name: Install
        run: go install github.com/Ladicle/tcardgen@latest
      - name: Generate Open Graph Images
        run: tcardgen -f ./tcardgen/font -o ./static/img -c ./tcardgen/template/template.yaml -t ./tcardgen/template/template.png ./content/posts/**/*.md
      - name: Build
        run: hugo --gc --minify --cleanDestinationDir
      - name: Compress Image
        run: find . -name "*.png" -exec bash -c 'file="{}"; npx @squoosh/cli --oxipng auto "$file"' \;
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: public
          publish_dir: ./public
          force_orphan: true